apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
    - port: 80            # k8s 内部访问端口
      targetPort: 8080    # 容器内部端口（应用端口）
      nodePort: 30080     # 暴露给外网的端口

